### ISSUE TITLE
Best strategy for time course experiment

### ISSUE THREAD

**Issue by MaestSi** [ZhenxingGuo0015/TRESS#3]
Dear @ZhenxingGuo0015,
I have an experimental design with 3 replicates and 6 time points. Which of these two strategies seems more suitable to you?
- Compare replicates of each sample at a specific time point VS replicates at time point = 0h, and repeat both the fit and the test for each time point
- Perform a single fit creating dummy variables for each time point, with name time_point_1h, time_point_2h, etc, with values set at a specific value for the corresponding time point, and "other" for remaining time points, defining a model with all these variables, and then performing pairwise comparisons between time points using a contrast vector? For example:
```
> str(variable_treatment_full)
'data.frame':	18 obs. of  6 variables:
 $ time_0h : chr  "0h" "0h" "0h" "other" ...
 $ time_1h : chr  "other" "other" "other" "1h" ...
 $ time_2h : chr  "other" "other" "other" "other" ...
 $ time_4h : chr  "other" "other" "other" "other" ...
 $ time_8h : chr  "other" "other" "other" "other" ...
 $ time_16h: chr  "other" "other" "other" "other" ... 

 > model_treatment_full
~1 + time_0h + time_1h + time_2h + time_4h + time_8h + time_16h

> Contrast_1h
[1] 0 1 0 0 0 0
```

Thanks in advance,
Simone

**Comment by ZhenxingGuo0015** [comment]
Hi @MaestSi,

Thanks for trying TRESS for DMR calling. Could you please install our latest version TRESS_1.3.7? (currently on github and also on Bioconductor in the development version). 
For your question, both settings are supported by TRESS. For the second one, you can simply specify one ``predictor" variable as below
```r
variable = data.frame(predictor = rep(paste0(c(0,1,2,4,8,16), "h"), each = 3))
variable$predictor = factor(variable$predictor, paste0(c(0,1,2,4,8,16), "h"))
model = ~1+predictor
## check the design matrix
model.matrix(model, variable)
```
Based on above setting, you can use different contrasts to compare each time point with 0h. 
```r
# 1h vs 0h
Contrast = c(0,1,0,0,0,0)
# 2h vs 0h
Contrast = c(0,0,1,0,0,0)
#4h vs 0h
Contrast = c(0,0,0,1,0,0)
#8h vs 0h
Contrast = c(0,0,0,0,1,0)
#16h vs 0h
Contrast = c(0,0,0,0,0,1)
```
 I would suggest setting 1 if you are only interested in the comparison between time point ih with 0h. If you want a  comprehensive comparison between any two time points, then setting 2 is more convenient. In general, setting 2 takes longer time to run because it will need to collect candidates from samples under all conditions, and then fit model on a large number of candidates. Because candidates (both the regions and the numbers) from all conditions differ from those obtained from only two conditions, the results may also be slightly different from that obtained from setting 1.


Best,
Zhenxing

**Comment by MaestSi** [comment]
Thank you!
Best,
Simone
